### ISSUE TITLE
Pressing CapsLock in the demo textbox writes "CapsLock"

### ISSUE THREAD

**Issue by nico-abram** [emilk/emigui#11]
I decided to test it after I saw capslock made an event shown as Text("CapsLock") in the raw state window while mashing the keyboard

**Comment by nico-abram** [comment]
Also happens with Insert

**Comment by nico-abram** [comment]
And NumLock

**Comment by nico-abram** [comment]
And Pause and ScrollLock

**Comment by emilk** [comment]
Thanks!

This is because when listening to the `keydown` event, the web sends me the name of the key in the same field as the text they represent. So if you press the `F` key we get either `"f"` or `"F"` (depending on shift/capslock state) and I get `"F1"` when someone pressed the "F1" key, `"CapsLock"` when someone pressed the `CapsLock` key, and so on. This sucks. Maybe there is some other event I should be listening to instead, but reading web/JS docs makes me sad, so I won't dig any deeper at this point.

Instead I'll keep black-listing the names of keys which aren't real text. *sigh*

Fixed in https://github.com/emilk/emigui/commit/f693a558c5990c22fb983b5f6fa20a58aff78f69
