### ISSUE TITLE
Windows move when clicking on widget

### ISSUE THREAD

**Issue by Uriopass** [emilk/emigui#5]
When selecting and holding on a widget, the window sometimes moves with it.  
Maybe this is the expected behavior, but it's very frustrating when you just want to click on a widget and accidentally move the mouse.  
Same goes for scrolling in the window.

https://i.imgur.com/dTxPGeA.gifv

**Comment by emilk** [comment]
It is intended behavior to move the window when dragging a non-draggable widget (like a checkbox). It makes moving windows and scrolling an area with your finger a lot simpler.

There are [two thresholds](https://github.com/emilk/emigui/blob/master/egui/src/input.rs#L3:L6) to decide what is a click and what is a drag. Perhaps they need tweaking so that a click is not accidentally interpreted as a drag by Egui.
