### ISSUE TITLE
winit backend

### ISSUE THREAD

**Issue by Uriopass** [emilk/emigui#6]
[winit](https://github.com/rust-windowing/winit) is a very popular windowing crate, it would be easier to jump into emigui if it existed.

**Comment by emilk** [comment]
Since glium is using winit, and I have a glium example, I sort of already have this. Winit is not enough of a backend by itself, that only covers the input, you also need to have something for the rendering (hence glium).

Anyway, the glium example is using and old glium version (I haven't prioritized updating it), so maybe it would be nicer to replace it with Winit plus $SOMETHING for the rendering, but I don't know that that $SOMETHING would be.

PRs welcome.

**Comment by emilk** [comment]
I've updated to the latest glium and winit now. Since egui supports winit via the `egui_glium` and there is no specific other thing (winit + FOO) being requested, I'll close this issue for now.
